# Generated by Django 3.2 on 2023-05-05 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time', models.FloatField(default=0, editable=False)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time', models.FloatField(default=0, editable=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
